### ISSUE TITLE
Method to call CKAN action API

### ISSUE THREAD

**Issue by rufuspollock** [datopian/ckan-client-js#10]
We can copy this from old okfn/ckan.js

## Acceptance

* [x] `async client.action(actionName, payload, useHttpGet=false)` calls CKAN action API and returns the result
* [x] (?) Support for forcing http get

~~[ ] the method is documented in code and README~~
Created a separate issue for this #22 

## Tasks

* [x] Tests (copy from okfn/ckan.js)
  * [x] Node

~~* [ ] Browser (?)~~
 I don't think we need this for now, because the implementation of `action()` is platform agnostic, i.e. there is no any platform related implementation for now. 

* [x] Implement the method
* [x] Support for postType=GET (like ckan.js has)

**Comment by mariorodeghiero** [comment]
```
const ActionApi = {

  // Call the ckan api actions ie. 'package_create'
  action: async (baseUrl, authToken, actionType, data) => {
    const path = `/api/3/action/${actionType}`
    const config = {
      headers: {
        'Content-Type': 'application/json;charset=utf-8',
        Authorization: authToken,
      }
    }
    const body = JSON.stringify(data)

    const response = await axios.post(`${baseUrl}${path}`, data, config)
    if (!response.data.success) {
      throw `Action response: ${response.statusText}`
    }

    return response.data
  },
}
``

**Comment by rufuspollock** [comment]
The `action` method should be part of `Client` class

```javascript=
class Client {

  // Call the ckan api actions ie. 'package_create'
  action: async(actionType, payload, forceHttpGet=false) => {
    const path = `/api/3/action/${actionType}`
    const config = {
      headers: {
        'Content-Type': 'application/json;charset=utf-8',
        Authorization: this.authToken,
      }
    }

    const body = JSON.stringify(data)
    
    // TODO: if forceHttpGet then ...
    
    const response = await axios.post(`${baseUrl}${path}`, data, config)
    if (!response.data.success) {
      throw `Action response: ${response.statusText}`
    }
    return response.data
  },
}
```

**Comment by kmanaseryan** [comment]
Covered in #14
