### ISSUE TITLE
Push dataset metadata client.push(datasetMetadata) 

### ISSUE THREAD

**Issue by rufuspollock** [datopian/ckan-client-js#11]
`client.push(datasetMetadata)` function works which takes dataset JS object (in f11s format) and puts it to CKAN datastore

## Acceptance

* [x] `client.push(datasetMetadata)` that updates an (existing) dataset. If Dataset exists raises exception with that info
* [ ] `client.create(datasetNameOrMetadata)` that creates a "project" (with associated dataset).

## Tasks

* [x] Convert from f11s metadata to ckan metadata 
* [x] Call action api method and save that metadata and return response

**Comment by mariorodeghiero** [comment]
Fixed!
you can see the changes in the PR [a47bfb2](https://github.com/datopian/ckan-client-js/commit/a47bfb2cca7db642cfb52559bc4dfe150cbef678)
