### ISSUE TITLE
Update README to document the usage of action(), retrieve(), put() and create() functions

### ISSUE THREAD

**Issue by kmanaseryan** [datopian/ckan-client-js#22]
## Acceptence criteria

The README include documentation for 

- [x] `create()`
- [x] `retrieve()`
- [x] `push()`
- [x] `action()`
- [x] Has a more detailed usage example e.g. adding a resource with data file to a dataset (could just copy code from #4)
- [x] Instructions for using in browser and node 

## Task

- [x] Update the readme accordingly
