### ISSUE TITLE
Update README for better explanation of using methods 

### ISSUE THREAD

**Issue by kmanaseryan** [datopian/ckan-client-js#29]
### Acceptance criteria

- [x] In the README I can see how to use in the browser - including it as a script
- [ ] Used jsdoc2md which documents the methods in README
- [x] `pushBlob` is documented 
- [x] Node part of how to use it is now more clear

### Tasks

- [x] Update README for the browser 
- [ ] Use jsdoc2md to convert the comments into md in README
- [x] Document `pushBlob` method in README
- [x] Update Node part re how to use it
