### ISSUE TITLE
Use browser file object as a data instead of whole buffer on upload

### ISSUE THREAD

**Issue by kmanaseryan** [datopian/ckan-client-js#32]
Originally this issue came from 
https://github.com/datopian/data.js/issues/89

We had two issues with this:
- [x] Unable to generate hash for large files. (This is fixed in data.js) 
- [x] Unable to upload large file (This needs to be fixed here)

## Acceptence criteria 
- [x] Able to upload large file (600mb+)
- [x] The existing tests should pass 

## Tasks
- [x] Update upload method so that it won't use the buffer instead it will use the original browser file object

## Analysis 
The thing is that when we upload a file, we read it as buffer and then pass this to HTTP request. However when the file is too large (e.g. 600+) the browser fails to read it, depending on the memory capacity. Now instead of passing the buffer we should pass the original browser file object and stay away from reading the file contnet. The rest will be handled by the HTTP request. It worth to mention that original issue is not produced at this stage, it happened even in earlier step, during generating the hash. Since for the hash we also used to use the whole buffer, initially it failed here first. However we got improvements here, so instead of reading the whole buffer, now **data.js** lib supports reading the file buffer chunk by chunk which gives us the ability to read arbitrary size of file and hash it. So as you can see remains only the last checkpoint to cover.

**Comment by mariorodeghiero** [comment]
@kmanaseryan I think this issue can be closed once the PR is merged.

Test locally with 1.9Gb

![Screenshot from 2020-11-04 19-33-47](https://user-images.githubusercontent.com/24671133/98176377-315e5600-1ed7-11eb-9a8a-7881417ff02c.png)
