### ISSUE TITLE
retrieve method for dataset metdata

### ISSUE THREAD

**Issue by kmanaseryan** [datopian/ckan-client-js#7]
Implement retrieve dataset function as described in EPIC #4 

## Aceptence criteria

- [x] `client.retrieve(datasetNameOrId)` returning a frictionless formatted dataset object.

## Tasks

- [x] Write a function which receives the data id or dataset name as parameter and makes the relevant request to CKAN server to get the dataset. 
- [x] Converts the result to frictionless format
- [x] Write the test to assert the above implementation

## Analysis

Pseudo-code

```
client.retrieve( ... )
    await result = this.action(`package_get`, name)
    return ckan2f11s.dataset(result.package)
```
