### ISSUE TITLE
Implement get resource

### ISSUE THREAD

**Issue by kmanaseryan** [datopian/ckan-client-js#8]
Implement get resource function as described in EPIC #4 

## Aceptence criteria

- [ ] When the resource id or dataset id and resource name is/are passed return the resource json

## Tasks

- [ ] Write a function which receives the resource id or dataset id & resource name and makes the relevant request to CKAN server to get the dataset. 
- [ ] Write the test to assert the above implementation

**Comment by rufuspollock** [comment]
WONTFIX. This is low priority for now and we don't need it. We can reopen if needed.
